import { useAuth } from "@/_core/hooks/useAuth";
import { AppShell } from "@/components/AppShell";
import { PageLoader } from "@/components/PageLoader";
import { Button } from "@/components/ui/button";
import { getLoginPath } from "@/const";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCheck, ExternalLink, LogIn, MailOpen } from "lucide-react";
import { Link } from "wouter";

export default function Notifications() {
  const { isAuthenticated, loading } = useAuth();
  const utils = trpc.useUtils();
  const notifications = trpc.notifications.list.useQuery({ limit: 40 }, { enabled: isAuthenticated });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: async () => { await Promise.all([utils.notifications.list.invalidate(), utils.notifications.unreadCount.invalidate()]); } });
  const markAll = trpc.notifications.markAllRead.useMutation({ onSuccess: async () => { await Promise.all([utils.notifications.list.invalidate(), utils.notifications.unreadCount.invalidate()]); } });

  if (loading) return <AppShell><PageLoader /></AppShell>;
  if (!isAuthenticated) return <AppShell><div className="container py-24"><div className="mx-auto max-w-xl rounded-[2rem] border border-cyan-300/15 bg-slate-950/80 p-8 text-center"><LogIn className="mx-auto h-9 w-9 text-cyan-300" /><h1 className="mt-5 text-3xl font-black text-white">Sign in to view alerts</h1><p className="mt-3 text-slate-400">Matches, claims, and staff decisions appear here.</p><Button asChild className="mt-7 rounded-full bg-gradient-to-r from-violet-500 to-cyan-400"><Link href={getLoginPath("/notifications")}>Sign in securely</Link></Button></div></div></AppShell>;

  return <AppShell><section className="border-b border-white/5 bg-[radial-gradient(circle_at_20%_0%,rgba(139,92,246,.16),transparent_30%),linear-gradient(180deg,#0b0717,#03070d)] py-14"><div className="container flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-black uppercase tracking-[0.22em] text-violet-300">Notification center</p><h1 className="mt-3 text-4xl font-black text-white sm:text-6xl">Stay in the loop.</h1><p className="mt-4 text-slate-400">Automatic alerts for item matches, submitted claims, and staff decisions.</p></div><Button onClick={() => markAll.mutate()} disabled={markAll.isPending} variant="outline" className="border-cyan-300/20 bg-cyan-300/5 text-cyan-100"><CheckCheck className="mr-2 h-4 w-4" />Mark all read</Button></div></section><section className="container py-10">{notifications.isLoading ? <PageLoader label="Loading notifications" /> : notifications.error ? <div className="mx-auto max-w-3xl rounded-3xl border border-rose-400/20 bg-rose-400/5 p-6 text-rose-100">Unable to load notifications: {notifications.error.message}</div> : notifications.data?.length ? <div className="mx-auto max-w-4xl space-y-4">{notifications.data.map(notification => <article key={notification.id} className={`rounded-[1.5rem] border p-5 transition ${notification.isRead ? "border-white/7 bg-slate-950/55" : "border-cyan-300/18 bg-cyan-300/[0.055] shadow-[0_0_30px_rgba(34,211,238,.06)]"}`}><div className="flex gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${notification.isRead ? "bg-white/5 text-slate-400" : "bg-gradient-to-br from-violet-500/25 to-cyan-400/20 text-cyan-200"}`}><Bell className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-white">{notification.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{notification.message}</p></div><span className="text-xs text-slate-600">{new Date(notification.createdAt).toLocaleString()}</span></div><div className="mt-4 flex flex-wrap gap-2">{notification.itemId ? <Button asChild size="sm" variant="outline" className="border-white/10 bg-white/[0.03]"><Link href={`/items/${notification.itemId}`}>Open item <ExternalLink className="ml-2 h-3.5 w-3.5" /></Link></Button> : null}{!notification.isRead ? <Button size="sm" variant="ghost" onClick={() => markRead.mutate({ id: notification.id })} className="text-cyan-200"><MailOpen className="mr-2 h-3.5 w-3.5" />Mark read</Button> : null}</div></div></div></article>)}</div> : <div className="mx-auto max-w-3xl rounded-[2rem] border border-dashed border-white/10 py-20 text-center"><Bell className="mx-auto h-9 w-9 text-cyan-300/50" /><h2 className="mt-5 text-xl font-bold text-white">No notifications yet</h2><p className="mt-2 text-sm text-slate-400">New matches and claim updates will appear here.</p></div>}</section></AppShell>;
}
